wip: Test Wrapped Service
`test_net` now fails with:
```
/Volumes/workplace/ryan-new-world/polymorph/TestModels/resources/runtimes/net/Generated/Wrapped/TypeConversion.cs(190,13): error CS0246: The type or namespace name 'WrappedNativeWrapper_SimpleResource' could not be found (are you missing a using directive or an assembly reference?) [/Volumes/workplace/ryan-new-world/polymorph/TestModels/resources/runtimes/net/SimpleResources.csproj]
```

Which I suspect is smithy-dotnet issue.
It may be that smithy-dotnet assumes all resources
are extendable.